package com.madokasoftwares.mvvmkotlin.data


import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize
//import androidx.versionedparcelable.VersionedParcelize
import java.text.DateFormat

@Entity(tableName = "task_table") //storing our task in sqlDB
@Parcelize //makes it possible to send this objects between different fragments
data class Task (
    val name:String,
    val important:Boolean,
    val completed:Boolean,
    val created:Long = System.currentTimeMillis(),

    @PrimaryKey(autoGenerate = true) val id:Int = 0 //each item will have a primary key which will be autogenerated
):Parcelable
{
    val createdDateFormatted:String  //formatting our time in date time
    get() = DateFormat.getDateInstance().format(created) //overriding the get method
}